name: Deploy Viewer to GitHub Pages

on:
  push:
    branches: [ master ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate latest graph (Lesson 1)
        env:
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
        run: |
          python lessons/01_hello_chain/code.py --text "Deploy preview: neural networks in one sentence"

      - name: Generate latest graph (Lesson 2) 
        env:
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
        run: |
          python lessons/02_prompt_patterns/code.py --text "Deploy preview: What are the main differences between supervised and unsupervised learning?"

      - name: Install viewer deps
        working-directory: viewer
        run: |
          npm ci

      - name: Copy lesson artifacts to viewer
        run: |
          mkdir -p viewer/public/lessons
          cp lessons/01_hello_chain/graph.json viewer/public/lessons/01_hello_chain.json
          cp lessons/02_prompt_patterns/graph.json viewer/public/lessons/02_prompt_patterns.json
          # Create a lessons manifest for static deployment
          echo '{"lessons":[{"id":"01_hello_chain","lesson_id":"01_hello_chain","title":"Hello Chain"},{"id":"02_prompt_patterns","lesson_id":"02_prompt_patterns","title":"Prompt Patterns"}]}' > viewer/public/lessons/index.json

      - name: Build viewer (static)
        working-directory: viewer
        env:
          # Static Pages build has no API; the app will load lessons from public/lessons/
          VITE_API_BASE_URL: ""
        run: npm run build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: viewer/dist

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
